language: node_js
node_js:
  - "8"

cache:
  paths:
    - node_modules/

before_script:
  - chmod +x ./scripts/postinstall.test.sh

script:
  - npm run lint
  - npm test
  - npm run production
  - ./scripts/postinstall.test.sh
